### ISSUE TITLE
Build fails: cannot find function `copy_string` in module `crate::clipboard`

### ISSUE THREAD

**Issue by yurivict** [extrawurst/gitui#461]
Version 0.11.0 fails to build on FreeBSD 12.2 with rust-1.48.0:

```

error[E0425]: cannot find function `copy_string` in module `crate::clipboard`
   --> src/components/commitlist.rs:128:31
    |
128 |             crate::clipboard::copy_string(&e.hash_short)?;
    |                               ^^^^^^^^^^^ not found in `crate::clipboard`

error[E0425]: cannot find function `copy_string` in module `crate::clipboard`
   --> src/components/diff.rs:262:35
    |
262 |                 crate::clipboard::copy_string(
    |                                   ^^^^^^^^^^^ not found in `crate::clipboard`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `gitui`
```

**Comment by extrawurst** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/776816/102868595-a7dcf600-443a-11eb-8aa2-d9455fa7fa5e.png">
seems that does not cut it on freebsd

**Comment by extrawurst** [comment]
@yurivict can you please test branch https://github.com/extrawurst/gitui/tree/freebsd-fix ?

**Comment by yurivict** [comment]
Now it fails like this:
```
error[E0432]: unresolved import `which`
  --> src/clipboard.rs:53:9
   |
53 |     use which::which;
   |         ^^^^^ use of undeclared crate or module `which`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `gitui`

```

**Comment by extrawurst** [comment]
next try: https://github.com/extrawurst/gitui/commit/fbba2d01c9984b1f133d83c6c02ad5c099fd5794

**Comment by yurivict** [comment]
fbba2d0 works.

**Comment by extrawurst** [comment]
Any chance you might be interested in contributing integrating FreeBSD into the CI to prevent this in the future?

**Comment by yurivict** [comment]
It looks like GitHub CI currently only supports Linux, MacOS, and Windows:
https://github.com/features/actions

**Comment by extrawurst** [comment]
@yurivict can you boot up freebsd inside docker? then it should be doable in GitHub Actions

**Comment by yurivict** [comment]
AFAIK docker doesn't support FreeBSD.
