### ISSUE TITLE
undefined reference to `git_branch_name_is_valid'

### ISSUE THREAD

**Issue by leecannon** [extrawurst/gitui#853]
**Describe the bug**
After commit d42b00389c960b0aac1b0d0fa03ee07de5c3f7a8 (found by git bisect) compilation fails with the error:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/lee/src/gitui/target/release/deps/gitui-949dd8264f23690b.gitui.f8472fbe-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/lee/src/gitui/target/release/deps" "-L" "/usr/lib" "-L" "/home/lee/src/gitui/target/release/build/libssh2-sys-0a8acf086ff3fcc8/out/build" "-L" "/home/lee/src/gitui/target/release/build/openssl-sys-5066e3da5d8b1711/out/openssl-build/install/lib" "-L" "/home/lee/src/gitui/target/release/build/sys-info-0e15c68dea07eaab/out" "-L" "/home/lee/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcDHIJrs/libsys_info-9829c21529521aca.rlib" "/tmp/rustcDHIJrs/liblibssh2_sys-839056c310076187.rlib" "/tmp/rustcDHIJrs/libopenssl_sys-62ae95b1ef6c5efb.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/lee/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-96219fb718f2f3e8.rlib" "-Wl,-Bdynamic" "-lgit2" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/lee/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/lee/src/gitui/target/release/deps/gitui-949dd8264f23690b" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/lee/src/gitui/target/release/deps/gitui-949dd8264f23690b.gitui.f8472fbe-cgu.0.rcgu.o: in function `gitui::app::App::draw_popups':
          gitui.f8472fbe-cgu.0:(.text._ZN5gitui3app3App11draw_popups17h582edd87cb015eb4E+0x3692): undefined reference to `git_branch_name_is_valid'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `gitui` due to previous error
```

**Context (please complete the following information):**
 - OS/Distro + Version: Arch
 - GitUI Version: master
 - Rust version: 1.56.0-nightly (0035d9dce 2021-08-16)
 - libgit2 version: 1.1.1
 - gcc version: 11.1.0

**Comment by extrawurst** [comment]
That’s an upstream issue: 
You essentially cannot link against some system libgit2 version

**Comment by alerque** [comment]
Just bumped into this issue trying to update the official package for Arch Linux. It would be much appreciated if we could refrain from relying on things that are not released in dependencies yet. Keeping a devel branch with the goodies to be merged as soon as upstream releases them would be preferable.

Is there any chance of working around this by making some adjustments and not using any of the APIs in unreleased versions yet? Is the functionality so critical it can't be accomplished another way?

**Comment by extrawurst** [comment]
we will soon get a new git2-rs release providing us with the necessary functions. will followup with a release myself then to fix these issues

**Comment by extrawurst** [comment]
ok we are getting closer. only a git2-rs release missing: https://github.com/rust-lang/git2-rs/pull/745

after that I will do a release and bundling up a gitui release in distros should be easier again

**Comment by extrawurst** [comment]
in the light of this: https://github.com/libgit2/libgit2sharp/pull/1907#issuecomment-913095485
I might wait a week to see if libgit2 releases a patch version that changes the memory layout again.

**Comment by jairbubbles** [comment]
I don't know if you've seen but the new method `git_branch_name_is_valid`  was not exported correctly in v1.2.0 (see https://github.com/libgit2/libgit2/pull/6032)

**Comment by extrawurst** [comment]
> I don't know if you've seen but the new method `git_branch_name_is_valid` was not exported correctly in v1.2.0 (see [libgit2/libgit2#6032](https://github.com/libgit2/libgit2/pull/6032))

actually `git_remote_name_is_valid` was exported incorrectly so it should not affect us

**Comment by jairbubbles** [comment]
You're totally right! 😅

**Comment by extrawurst** [comment]
@leecannon @alerque can you verify this on current master before I box it up into a release?

**Comment by alerque** [comment]
I can confirm the current Git HEAD builds against system-installed libgit2 now as long as the latter is v1.2.0 not v1.1.1.

**Comment by alerque** [comment]
Segfaulting is a different issue. The issue above is it wouldn't even build. Segfaulting at runtime is different and you should open a separate issue about your problem.
