### ISSUE TITLE
0.10.0 build error

### ISSUE THREAD

**Issue by tim77** [extrawurst/gitui#257]
**Describe the bug**
`0.10.0` won't compile. This error during build:

```rust
 Compiling gitui v0.10.0 (/builddir/build/BUILD/gitui-0.10.0)
error[E0658]: `if` is not allowed in a `const fn`
   --> src/cmdbar.rs:128:9
    |
128 | /         if self.expandable && self.expanded {
129 | |             self.lines
130 | |         } else {
131 | |             1_u16
132 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: `match` is not allowed in a `const fn`
  --> src/components/diff.rs:42:9
   |
42 | /         match self {
43 | |             Self::Single(start) | Self::Multiple(start, _) => *start,
44 | |         }
   | |_________^
   |
   = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: or-pattern is not allowed in a `const fn`
  --> src/components/diff.rs:43:13
   |
43 |             Self::Single(start) | Self::Multiple(start, _) => *start,
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: `match` is not allowed in a `const fn`
  --> src/components/diff.rs:48:9
   |
48 | /         match self {
49 | |             Self::Single(end) | Self::Multiple(_, end) => *end,
50 | |         }
   | |_________^
   |
   = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: or-pattern is not allowed in a `const fn`
  --> src/components/diff.rs:49:13
   |
49 |             Self::Single(end) | Self::Multiple(_, end) => *end,
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: `if` is not allowed in a `const fn`
   --> src/components/diff.rs:464:9
    |
464 | /         if hunk_min <= min && hunk_max >= max {
465 | |             return true;
466 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: `if` is not allowed in a `const fn`
   --> src/components/diff.rs:469:9
    |
469 | /         if (hunk_min >= min && hunk_min <= max)
470 | |             || (hunk_max >= min && hunk_max <= max)
471 | |         {
472 | |             return true;
473 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: `match` is not allowed in a `const fn`
   --> src/components/filetree.rs:209:9
    |
209 | /         match item_type {
210 | |             StatusItemType::Modified => 'M',
211 | |             StatusItemType::New => '+',
212 | |             StatusItemType::Deleted => '-',
213 | |             StatusItemType::Renamed => 'R',
214 | |             StatusItemType::Typechange => ' ',
215 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error[E0658]: `if` is not allowed in a `const fn`
   --> src/ui/style.rs:128:9
    |
128 | /         if selected {
129 | |             style.bg(self.selection_bg)
130 | |         } else {
131 | |             style
132 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error: aborting due to 9 previous errors

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `gitui v0.10.0 (/builddir/build/BUILD/gitui-0.10.0)`, intermediate artifacts can be found at `/builddir/build/BUILD/gitui-0.10.0/target`

Caused by:
  could not compile `gitui`.
```

- [Full build log](https://download.copr.fedorainfracloud.org/results/atim/gitui/fedora-32-x86_64/01639681-gitui/builder-live.log.gz)

**To Reproduce**
Try to build `0.10.0` with latest rust-1.46 version.

**Expected behavior**
Successful build.

**Context (please complete the following information):**
 - OS/Distro + Version: `Fedora 32`
 - GitUI Version `0.10.0`
 - Rust version: `1.46`

**Additional context**

**Comment by extrawurst** [comment]
Can you share your `rustc --version` output? It looks like you're actually not using the latest stable rust 🤔

**Comment by ignatenkobrain** [comment]
Rust 1.46 is needed indeed.

**Comment by tim77** [comment]
> Can you share your `rustc --version` output? It looks like you're actually not using the latest stable rust thinking

Oops, my apologies, in compiles fine on Rawhide where rust-1.46 but error was another error (missed `xcb-devel` package). Thanks a lot. Building.
